version: '3.8'

services:
  minio:
    container_name: class-minio
    image: minio/minio:RELEASE.2022-12-12T19-27-27Z
    restart: always
    env_file:
      - .env
    ports:
      - "${MINIO_API_PORT}:9000"  # API / S3-compatible endpoint
      - "${MINIO_CONSOLE_PORT}:9001"  # Console / Web UI
    volumes:
      - minio_data:/minio-data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /minio-data --address ":9000" --console-address ":9001"

volumes:
  minio_data:
    driver: local
